"""add playlists, likes, and listening history

Revision ID: 4bf1af940d5b
Revises: c402cc3d41e5
Create Date: 2025-12-24 23:31:08.504609

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4bf1af940d5b'
down_revision = 'c402cc3d41e5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('playlists',
                    sa.Column('id', sa.UUID(), nullable=False),
                    sa.Column('user_id', sa.UUID(), nullable=False),
                    sa.Column('name', sa.String(length=150), nullable=False),
                    sa.Column('is_public', sa.Boolean(), nullable=False),
                    sa.Column('created_at', sa.DateTime(),
                              server_default=sa.text('now()'), nullable=False),
                    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('listening_history',
                    sa.Column('id', sa.UUID(), nullable=False),
                    sa.Column('user_id', sa.UUID(), nullable=False),
                    sa.Column('track_id', sa.UUID(), nullable=False),
                    sa.Column('played_at', sa.DateTime(),
                              server_default=sa.text('now()'), nullable=False),
                    sa.ForeignKeyConstraint(['track_id'], ['tracks.id'], ),
                    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('playlist_tracks',
                    sa.Column('playlist_id', sa.UUID(), nullable=False),
                    sa.Column('track_id', sa.UUID(), nullable=False),
                    sa.Column('added_at', sa.DateTime(),
                              server_default=sa.text('now()'), nullable=False),
                    sa.ForeignKeyConstraint(
                        ['playlist_id'], ['playlists.id'], ),
                    sa.ForeignKeyConstraint(['track_id'], ['tracks.id'], ),
                    sa.PrimaryKeyConstraint('playlist_id', 'track_id')
                    )
    op.create_table('track_likes',
                    sa.Column('user_id', sa.UUID(), nullable=False),
                    sa.Column('track_id', sa.UUID(), nullable=False),
                    sa.Column('liked_at', sa.DateTime(),
                              server_default=sa.text('now()'), nullable=False),
                    sa.ForeignKeyConstraint(['track_id'], ['tracks.id'], ),
                    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
                    sa.PrimaryKeyConstraint('user_id', 'track_id')
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('track_likes')
    op.drop_table('playlist_tracks')
    op.drop_table('listening_history')
    op.drop_table('playlists')
    # ### end Alembic commands ###
